dingding:
  datasource:
    host: localhost
    port: 3306
    database: dingding_catering
    username: root
    password: 123456
  alioss:
    region: cn-beijing
    bucket-name: dingding-catering
    access-key-id: LTAI5t9x4s5rg2aEfRKfpqbD
    access-key-secret: l5p5wvcj1nVlt3wWDv68NO9mQ8JGxe
  redis:
    host: localhost
    port: 6379
  jwt:
    admin-secret-key: ewquoisalkdsdkljaslkdjalksjdlkasjldkjaslkdjalk
    admin-ttl: 7200000
    admin-token-name: token
    user-secret-key: qwoiursalkjdlxaslkdjvnlasdqsdasdsvadertqpwipots
    user-ttl: 7200000
    user-token-name: authentication
  wechat:
    appid: wx75ff47dbae1adc47
    secret: b282dccbe6ac68277b166d8de10d41e0
