server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${dingding.datasource.host}:${dingding.datasource.port}/${dingding.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${dingding.datasource.username}
    password: ${dingding.datasource.password}
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall,config
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 12345678
  data:
    redis:
      host: ${dingding.redis.host}
      port: ${dingding.redis.port}
      database: 0

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.dingdingcatering.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      dingdingcatering:
        mapper: debug
        service: info
        controller: info
        interceptor: debug

dingding:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ${dingding.jwt.admin-secret-key}
    # 设置jwt过期时间
    admin-ttl: ${dingding.jwt.admin-ttl}
    # 设置前端传递过来的令牌名称
    admin-token-name: ${dingding.jwt.admin-token-name}

    user-secret-key: ${dingding.jwt.user-secret-key}
    user-ttl: ${dingding.jwt.user-ttl}
    user-token-name: ${dingding.jwt.user-token-name}
  alioss:
    region: ${dingding.alioss.region}`
    bucket-name: ${dingding.alioss.bucket-name}
    access-key-id: ${dingding.alioss.access-key-id}
    access-key-secret: ${dingding.alioss.access-key-secret}
  wechat:
    appid: ${dingding.wechat.appid}
    secret: ${dingding.wechat.secret}
